name: Java Compile and Run

on:
  push:
    paths:
      - '**.java'
      - '.github/workflows/java.yml'
  workflow_dispatch:

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Temurin Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile HelloWorld.java
        run: javac HelloWorld.java

      - name: Run HelloWorld
        run: java HelloWorld
